export const TAROT_CARDS = [
  // Major Arcana
  { name: 'The Fool', number: 0 },
  { name: 'The Magician', number: 1 },
  { name: 'The High Priestess', number: 2 },
  { name: 'The Empress', number: 3 },
  { name: 'The Emperor', number: 4 },
  { name: 'The Hierophant', number: 5 },
  { name: 'The Lovers', number: 6 },
  { name: 'The Chariot', number: 7 },
  { name: 'Strength', number: 8 },
  { name: 'The Hermit', number: 9 },
  { name: 'Wheel of Fortune', number: 10 },
  { name: 'Justice', number: 11 },
  { name: 'The Hanged Man', number: 12 },
  { name: 'Death', number: 13 },
  { name: 'Temperance', number: 14 },
  { name: 'The Devil', number: 15 },
  { name: 'The Tower', number: 16 },
  { name: 'The Star', number: 17 },
  { name: 'The Moon', number: 18 },
  { name: 'The Sun', number: 19 },
  { name: 'Judgement', number: 20 },
  { name: 'The World', number: 21 },

  // Minor Arcana - Wands
  { name: 'Ace of Wands', number: 22 },
  { name: 'Two of Wands', number: 23 },
  { name: 'Three of Wands', number: 24 },
  { name: 'Four of Wands', number: 25 },
  { name: 'Five of Wands', number: 26 },
  { name: 'Six of Wands', number: 27 },
  { name: 'Seven of Wands', number: 28 },
  { name: 'Eight of Wands', number: 29 },
  { name: 'Nine of Wands', number: 30 },
  { name: 'Ten of Wands', number: 31 },
  { name: 'Page of Wands', number: 32 },
  { name: 'Knight of Wands', number: 33 },
  { name: 'Queen of Wands', number: 34 },
  { name: 'King of Wands', number: 35 },

  // Minor Arcana - Cups
  { name: 'Ace of Cups', number: 36 },
  { name: 'Two of Cups', number: 37 },
  { name: 'Three of Cups', number: 38 },
  { name: 'Four of Cups', number: 39 },
  { name: 'Five of Cups', number: 40 },
  { name: 'Six of Cups', number: 41 },
  { name: 'Seven of Cups', number: 42 },
  { name: 'Eight of Cups', number: 43 },
  { name: 'Nine of Cups', number: 44 },
  { name: 'Ten of Cups', number: 45 },
  { name: 'Page of Cups', number: 46 },
  { name: 'Knight of Cups', number: 47 },
  { name: 'Queen of Cups', number: 48 },
  { name: 'King of Cups', number: 49 },

  // Minor Arcana - Swords
  { name: 'Ace of Swords', number: 50 },
  { name: 'Two of Swords', number: 51 },
  { name: 'Three of Swords', number: 52 },
  { name: 'Four of Swords', number: 53 },
  { name: 'Five of Swords', number: 54 },
  { name: 'Six of Swords', number: 55 },
  { name: 'Seven of Swords', number: 56 },
  { name: 'Eight of Swords', number: 57 },
  { name: 'Nine of Swords', number: 58 },
  { name: 'Ten of Swords', number: 59 },
  { name: 'Page of Swords', number: 60 },
  { name: 'Knight of Swords', number: 61 },
  { name: 'Queen of Swords', number: 62 },
  { name: 'King of Swords', number: 63 },

  // Minor Arcana - Pentacles
  { name: 'Ace of Pentacles', number: 64 },
  { name: 'Two of Pentacles', number: 65 },
  { name: 'Three of Pentacles', number: 66 },
  { name: 'Four of Pentacles', number: 67 },
  { name: 'Five of Pentacles', number: 68 },
  { name: 'Six of Pentacles', number: 69 },
  { name: 'Seven of Pentacles', number: 70 },
  { name: 'Eight of Pentacles', number: 71 },
  { name: 'Nine of Pentacles', number: 72 },
  { name: 'Ten of Pentacles', number: 73 },
  { name: 'Page of Pentacles', number: 74 },
  { name: 'Knight of Pentacles', number: 75 },
  { name: 'Queen of Pentacles', number: 76 },
  { name: 'King of Pentacles', number: 77 },
];
